### ISSUE TITLE
 На Meizu иногда  возникает ошибка при открытии формы оплаты

### ISSUE THREAD

**Issue by chim0380** [yoomoney/yookassa-android-sdk#17]
При открытии формы оплаты на телефонах Meizu иногда возникает ошибка:

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
android.widget.Editor.updateCursorPositionMz (Editor.java:7671)
android.widget.Editor.updateCursorsPositions (Editor.java:1963)
android.widget.TextView.getUpdatedHighlightPath (TextView.java:5856)
android.widget.TextView.onDraw (TextView.java:6048)
android.view.View.draw (View.java:17424)
android.view.View.updateDisplayListIfDirty (View.java:16363)

Марка: Meizu
Модель: M6T
Операционная система
Версия: 7.0

У себя в приложении была такая же ошибка, но после замены  всех **TextInputEditText** на **AppCompatEditText**  ошибки такого рода перестали появляться. 

Возможно и вашем случае нужно заменить данные поля.

**Comment by lynnfield** [comment]
Здравствуйте. Спасибо, что сообщили и предложили решение.

**Comment by iskandarshabaev** [comment]
Проблема должна пропасть в версии 5.1.0
Просьба переоткрыть issue в случае повторного воспроизведения ошибки.
