### ISSUE TITLE
 Ошибки при сохранения состояния IllegalStateException при использовании библиотеки

### ISSUE THREAD

**Issue by chim0380** [yoomoney/yookassa-android-sdk#27]
Время от времени (как в прежних версиях, так и  2.2.0 )возникают ошибки **KotlinNullPointerException** и **IllegalStateException**. Эти ошибки указаны в одном issue, так как вероятно они вызваны схожими причинами.

В нашем приложении библиотека используется внутри childFragment, то есть Activity->Fragment->childFragment. На первый взгляд это экзотичный случай использования и можно отмахнуться от ошибки, но на наш взгляд эта ошибка пересекается с более общей  [проблемой](https://github.com/yandex-money/yandex-checkout-android-sdk/issues/18) 
Эти ошибки составляют 90% от всех сбоев в нашем приложения.

Может допустимо для транзакции DialogFragment внутри вашей библиотеки использование commitAllowingStateLoss  вместо сommit?

**Ошибка**:
Unable to start activity ComponentInfo{ru.znakomstva_sitelove.app/ru.yandex.money.android.sdk.impl.CheckoutActivity}: kotlin.KotlinNullPointerException

**Часть стека**:
ru.yandex.money.android.sdk.impl.j.k.onCreate (Unknown Source:30)
android.support.v4.app.Fragment.performCreate (Fragment.java:2414)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1418)
android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1784)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1852)
android.support.v4.app.FragmentManagerImpl.dispatchStateChange (FragmentManager.java:3269)
android.support.v4.app.FragmentManagerImpl.dispatchCreate (FragmentManager.java:3223)
android.support.v4.app.Fragment.restoreChildFragmentState (Fragment.java:1526)
android.support.v4.app.Fragment.onCreate (Fragment.java:1497)
android.support.v4.app.DialogFragment.onCreate (DialogFragment.java:310)
android.support.v4.app.Fragment.performCreate (Fragment.java:2414)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1418)
android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1784)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1852)
android.support.v4.app.FragmentManagerImpl.dispatchStateChange (FragmentManager.java:3269)
android.support.v4.app.FragmentManagerImpl.dispatchCreate (FragmentManager.java:3223)
android.support.v4.app.FragmentController.dispatchCreate (FragmentController.java:190)
android.support.v4.app.FragmentActivity.onCreate (FragmentActivity.java:369)
android.support.v7.app.AppCompatActivity.onCreate (AppCompatActivity.java:85)
ru.yandex.money.android.sdk.impl.CheckoutActivity.onCreate (Unknown Source:106)
android.app.Activity.performCreate (Activity.java:7183)

**Ошибка**:
Fatal Exception: java.lang.IllegalStateException
Can not perform this action after onSaveInstanceState

**Стек**
Первый случай
android.support.v4.app.FragmentManagerImpl.checkStateLoss (FragmentManager.java:2080)
android.support.v4.app.FragmentManagerImpl.enqueueAction (FragmentManager.java:2106)
android.support.v4.app.FragmentManagerImpl.popBackStack (FragmentManager.java:821)
ru.yandex.money.android.sdk.impl.n$f.invoke (Unknown Source)
ru.yandex.money.android.sdk.a.a$i.invoke (Unknown Source)
ru.yandex.money.android.sdk.impl.b.run (Unknown Source)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)

Второй случай
android.support.v4.app.FragmentManagerImpl.checkStateLoss (FragmentManager.java:2080)
android.support.v4.app.FragmentManagerImpl.enqueueAction (FragmentManager.java:2106)
android.support.v4.app.BackStackRecord.commitInternal (BackStackRecord.java:683)
android.support.v4.app.BackStackRecord.commit (BackStackRecord.java:637)
android.support.v4.app.DialogFragment.show (DialogFragment.java:144)
ru.yandex.money.android.sdk.impl.CheckoutActivity.a (Unknown Source)
ru.yandex.money.android.sdk.impl.CheckoutActivity$a.invoke (Unknown Source)
ru.yandex.money.android.sdk.a.a$j.invoke (Unknown Source)
ru.yandex.money.android.sdk.impl.b.run (Unknown Source)

Данные о двух последних телефонах c этими ошибками:
Марка: Meizu
Модель: M3s
Ориентация: Вертикальная
Свободная оперативная память: 245.95 MB
Свободное место на диске: 3.92 GB
Операционная система
Версия: 5.1
Ориентация: Вертикальная
Root-доступ: Нет
Сбой
Дата: 2 мая 2019 г., 17:34:00

Устройство
Марка: motorola
Модель: Moto G (5S)
Ориентация: Вертикальная
Свободная оперативная память: 1.11 GB
Свободное место на диске: 16.09 GB
Операционная система
Версия: 7.1.1
Ориентация: Вертикальная
Root-доступ: Нет
Сбой
Дата: 2 мая 2019 г., 18:29:00

**Comment by Tetraquark** [comment]
Проблема, судя по всему, до сих пор актуальна. Получили такое же исключение с `KotlinNullPointerException`. В проекте используем версию 3.0.0. Стэк-трейс такой:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{*/ru.yandex.money.android.sdk.impl.CheckoutActivity}: kotlin.KotlinNullPointerException
       at android.app.ActivityThread.performLaunchActivity + 2856(ActivityThread.java:2856)
       at android.app.ActivityThread.handleLaunchActivity + 2931(ActivityThread.java:2931)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage + 1620(ActivityThread.java:1620)
       at android.os.Handler.dispatchMessage + 105(Handler.java:105)
       at android.os.Looper.loop + 173(Looper.java:173)
       at android.app.ActivityThread.main + 6698(ActivityThread.java:6698)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run + 240(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main + 782(ZygoteInit.java:782)

Caused by kotlin.KotlinNullPointerException
       at ru.yandex.money.android.sdk.impl.j.k.onCreate + 30(:30)
       at androidx.fragment.app.Fragment.performCreate + 2414(Fragment.java:2414)
       at androidx.fragment.app.FragmentManagerImpl.moveToState + 1418(FragmentManager.java:1418)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState + 1784(FragmentManager.java:1784)
       at androidx.fragment.app.FragmentManagerImpl.moveToState + 1852(FragmentManager.java:1852)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange + 3269(FragmentManager.java:3269)
       at androidx.fragment.app.FragmentManagerImpl.dispatchCreate + 3223(FragmentManager.java:3223)
       at androidx.fragment.app.Fragment.restoreChildFragmentState + 1526(Fragment.java:1526)
       at androidx.fragment.app.Fragment.onCreate + 1497(Fragment.java:1497)
       at androidx.fragment.app.DialogFragment.onCreate + 310(DialogFragment.java:310)
       at androidx.fragment.app.Fragment.performCreate + 2414(Fragment.java:2414)
```

**Comment by Winner28** [comment]
Доброго времени суток, поправим в ближайшем релизе

**Comment by iskandarshabaev** [comment]
Обновили библиотеку, проблема должна пропасть в версии 5.1.0.
Проверьте пожалуйста, в случае повторного воспроизведения просьба переоткрыть issue
