### ISSUE TITLE
The user 10205 does not meet the requirements to access device identifiers. com.yandex.metrica.impl.ob.he.<init>

### ISSUE THREAD

**Issue by Charmandik** [yoomoney/yookassa-android-sdk#54]
Fatal Exception: java.lang.SecurityException
getSerial: The user 10205 does not meet the requirements to access device identifiers.
com.yandex.metrica.impl.ob.he.<init>

Caused by android.os.RemoteException
Remote stack trace: at com.android.internal.telephony.TelephonyPermissions.reportAccessDeniedToReadIdentifiers(TelephonyPermissions.java:417) at com.android.internal.telephony.TelephonyPermissions.checkReadDeviceIdentifiers(TelephonyPermissions.java:349) at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers(TelephonyPermissions.java:274) at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers(TelephonyPermissions.java:251) at com.android.server.os.DeviceIdentifiersPolicyService$DeviceIdentifiersPolicy.getSerialForPackage(DeviceIdentifiersPolicyService.java:67)

Проявляется только на andorid 10

**Comment by Winner28** [comment]
Спасибо за информацию, поправим в ближайшем релизе

**Comment by iskandarshabaev** [comment]
Обновили у себя библиотеку com.yandex.android:mobmetricalib.
Должно помочь, просьба открыть issue снова в случае воспроизведения
