### ISSUE TITLE
ru.yandex.money.android.sdk.impl.h.t cannot be cast to ru.yandex.money.android.sdk.impl.contract.j

### ISSUE THREAD

**Issue by AdislanSaidov** [yoomoney/yookassa-android-sdk#56]
`
Fatal Exception: java.lang.ClassCastException
ru.yandex.money.android.sdk.impl.h.t cannot be cast to ru.yandex.money.android.sdk.impl.contract.j
ru.yandex.money.android.sdk.impl.contract.f$g.invoke (f.java)
ru.yandex.money.android.sdk.a.a$aa.invoke (a.java:13)
ru.yandex.money.android.sdk.impl.b.run (b.java:2)
android.os.Handler.handleCallback (Handler.java:873)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)`

Устройство
Марка: Xiaomi
Модель: Redmi Note 7
Ориентация: Вертикальная
Свободная оперативная память: 737.27 MB
Свободное место на диске: 1.14 GB
Операционная система
Версия: 9
Ориентация: Вертикальная
Root-доступ: Нет
Сбой
Дата: 16 июл. 2020 г., 19:47:00

**Comment by AdislanSaidov** [comment]
и второе:
`Fatal Exception: java.lang.ClassCastException
ru.yandex.money.android.sdk.impl.h.t cannot be cast to ru.yandex.money.android.sdk.impl.contract.n
ru.yandex.money.android.sdk.impl.n$g.invoke (n.java)
ru.yandex.money.android.sdk.a.a$aa.invoke (a.java:13)
ru.yandex.money.android.sdk.impl.b.run (b.java:2)
android.os.Handler.handleCallback (Handler.java:873)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)`

Устройство
Марка: Xiaomi
Модель: Mi A1
Ориентация: Вертикальная
Свободная оперативная память: 1.8 GB
Свободное место на диске: 1.03 GB
Операционная система
Версия: 9
Ориентация: Вертикальная
Root-доступ: Нет
Сбой
Дата: 11 июл. 2020 г., 19:38:00

**Comment by AdislanSaidov** [comment]
`Fatal Exception: java.lang.ClassCastException
ru.yandex.money.android.sdk.impl.h.t cannot be cast to ru.yandex.money.android.sdk.impl.contract.n
ru.yandex.money.android.sdk.impl.n$g.invoke (n.java)
ru.yandex.money.android.sdk.a.a$aa.invoke (a.java:13)
ru.yandex.money.android.sdk.impl.b.run (b.java:2)
android.os.Handler.handleCallback (Handler.java:873)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)`

Устройство
Марка: Xiaomi
Модель: Redmi Note 8T
Ориентация: Вертикальная
Свободная оперативная память: 1.18 GB
Свободное место на диске: 42.47 GB
Операционная система
Версия: 9
Ориентация: Вертикальная
Root-доступ: Нет
Сбой
Дата: 11 июл. 2020 г., 11:52:00

**Comment by iskandarshabaev** [comment]
Обновили библиотеку, проблема должна пропасть в версии 5.1.0
Просьба при повторном воспроизведении переоткрыть issue
