### ISSUE TITLE
java.lang.IllegalArgumentException: Tokenization parameter value must not be empty при попытки оплаты с google pay

### ISSUE THREAD

**Issue by arctic4x** [yoomoney/yookassa-android-sdk#58]
краш java.lang.IllegalArgumentException: Tokenization parameter value must not be empty при попытки оплаты с google pay

**Comment by Winner28** [comment]
Здравствуйте, можете приложить подробный stacktrace ошибки?

**Comment by iskandarshabaev** [comment]
Проверьте пожалуйста на версии 5.1.2
В случае если проблема воспроизведётся просьба переоткрыть issue
