### ISSUE TITLE
Не отображает способ оплаты SBERBANK

### ISSUE THREAD

**Issue by dgumarov** [yoomoney/yookassa-android-sdk#59]
Добрый день.
У меня такая ситуация: если включить все доступные методы оплаты, то SBERBANK в списке не отображается, если указать только SBERBANK, то видим серый крестик и надпись No available payment methods.

Я сейчас использую тестовый ключ, может это быть связано?

**Comment by Winner28** [comment]
Здравствуйте, подскажите, с боевым ключом проблема воспроизводится?

**Comment by iskandarshabaev** [comment]
Похоже проблема с боевым ключом не воспроизвелась, закрываю issue.
