### ISSUE TITLE
ClassNotFoundException для "ru.yoo.sdk.gui.widgetV2.dialog.DialogVisibleListener"

### ISSUE THREAD

**Issue by kavorka-cat** [yoomoney/yookassa-android-sdk#63]
Добрый день.

Подскажите, пожалуйста, как можно решить возникшую проблему с оплатой через кошелек:

Подключила согласно инструкции основные зависимости (ru.yoo.sdk.auth:auth:1.0.35, ru.yoo.sdk.kassa.payments:yookassa-android-sdk:5.0.1), подложила ui-lib-1.19.5.aar и ThreatMetrix Android SDK 5.4-73.aar)
При попытке оплаты через кошелек вылетает исключение:

"java.lang.ClassNotFoundException: Didn't find class "**ru.yoo.sdk.gui.widgetV2.dialog**.DialogVisibleListener" on path: DexPathList..."

Внутри ui-lib-1.19.5.aar есть DialogVisibleListener, но внутри пакета "**ru.yandex.money.widgetV2.dialog**" . Компоненты же из auth-библиотеки пытаются найти этот класс внутри пакета "ru.yoo.sdk.gui".

**Comment by iskandarshabaev** [comment]
Добрый день. Нужно обновить версию ui-lib. Попросите у менеджера по подключению файл с новой версией `ui-lib-1.20.2.aar` и добавьте её в папку libs вместо `ui-lib-1.19.5.aar`
