### ISSUE TITLE
No static method createTokenizeIntent$default

### ISSUE THREAD

**Issue by anonlatte** [yoomoney/yookassa-android-sdk#64]
После миграции появилась следующая проблема
`Caused by: java.lang.NoSuchMethodError: No static method createTokenizeIntent$default(Landroid/content/Context;Lru/yoo/sdk/kassa/payments/PaymentParameters;Lru/yoo/sdk/kassa/payments/TestParameters;Lru/yoo/sdk/kassa/payments/UiParameters;ILjava/lang/Object;)Landroid/content/Intent; in class Lru/yoo/sdk/kassa/payments/Checkout; or its super classes (declaration of 'ru.yoo.sdk.kassa.payments.Checkout' appears in /data/app/com.test.example-RYSTv6UpJXtgyVJm83LDHg==/base.apk!classes4.dex)`

Подскажите, пожалуйста, как её можно решить?

**Comment by DenisRang** [comment]
Изи фикс
```
val checkout =Checkout::class.java.newInstance() as Checkout
val method = Checkout::class.java.getDeclaredMethod("createTokenizeIntent", Context::class.java, PaymentParameters::class.java)
val intent = method.invoke(checkout,requireContext(), paymentParameters) as Intent
```

**Comment by anonlatte** [comment]
@DenisRang, спасибо! Не подумал так обращаться к методу

**Comment by iskandarshabaev** [comment]
Исправим в следующей версии
