### ISSUE TITLE
style/Theme.Yoo not found

### ISSUE THREAD

**Issue by dormantpanda** [yoomoney/yookassa-android-sdk#65]
При попытке добавить 
ru.yoo.sdk.auth:auth:1.0.35
Не может найти
 AAPT: error: resource style/Theme.Yoo (projectName:style/Theme.Yoo) not found.
В чём может быть проблема?

**Comment by s7aycool** [comment]
@dormantpanda попробуй добавить зависимость из статьи https://loudplay.atlassian.net/wiki/spaces/ARCH/pages/739508225/Yandex+SDK, а не зависимость из этого гитхаба

**Comment by dormantpanda** [comment]
@s7aycool К сожалению, нет доступа к confluence, не мог бы скинуть саму статью в каком-либо формате?

**Comment by iskandarshabaev** [comment]
Здравствуйте. Уточните пожалуйста, вы подключаете `yookassa-android-sdk` в свой проект или пытаетесь собрать проект с гитхаба?
Похоже на то, что вам не хватает библиотеки `ui-lib-1.20.2.aar`, её можно попросить у вашего менеджера по подключению.

**Comment by s7aycool** [comment]
@iskandarshabaev а какой правильный вариант - собирать с гитхаба или подключить yookassa-android-sdk?

**Comment by iskandarshabaev** [comment]
Если вам нужны платежи в вашем приложении, то нужно подключить sdk к себе в проект.
Собирать эту библиотеку повторно, нет необходимости.

**Comment by s7aycool** [comment]
@iskandarshabaev https://yookassa.ru/developers/payment-forms/android-sdk
вот в этой документации упоминается этот гитхаб. Причем там подключают checkout:4.0.1. И там же пишут подключить SDK из этого репозитория. Какой вариант правильный?

**Comment by iskandarshabaev** [comment]
@s7aycool По указанной ссылке не увидел никаких инструкций про подключение `checkout:4.0.1`.
Самая актуальная и правильная информация по подключению sdk находится в этом репозитории.
Версия библиотеки `com.yandex.money:checkout` больше поддерживаться не будет. Её переименовали в `ru.yoo.sdk.kassa.payments:yookassa-android-sdk:5.0.1`, теперь нужно использовать именно эту версию.

**Comment by TW1NGOdev** [comment]
> Здравствуйте. Уточните пожалуйста, вы подключаете `yookassa-android-sdk` в свой проект или пытаетесь собрать проект с гитхаба?
> Похоже на то, что вам не хватает библиотеки `ui-lib-1.20.2.aar`, её можно попросить у вашего менеджера по подключению.

Где можно узнать последние версии библиотек `ui-lib` и `ThreatMetrix Android SDK`? В репозитории указано `ui-lib-1.19.5.aar`

**Comment by s7aycool** [comment]
@iskandarshabaev потому что по указанной ссылке была удалена инфа про подключение checkout:4.0.1. Может быть не по этой ссылке, но где-то там была инструкция с checkout:4.0.1. Теперь её нигде нет.


![image](https://user-images.githubusercontent.com/59872947/101375620-abac3c80-38c0-11eb-8bb4-e7651606e1e3.png)

**Comment by iskandarshabaev** [comment]
@TW1NGOdev Подправили Readme и Migration.
Актуальные версии: 
- ui-lib-1.20.2.aar
- ThreatMetrix Android SDK 5.4-73.aar

**Comment by dormantpanda** [comment]
Всем спасибо, при использовании ui-lib-1.20.2.aar всё наладилось.
