### ISSUE TITLE
Загрузка платежа

### ISSUE THREAD

**Issue by dormantpanda** [yoomoney/yookassa-android-sdk#66]
Есть ли какой-либо путь сделать окно загрузки при оплате, например, банковской картой, после ввода её данных и клика по кнопке подтверждения на весь экран, а не в bottomSheet, как реализовано по умолчанию?

**Comment by iskandarshabaev** [comment]
На данный момент такой опции в sdk нет. Подскажите, для чего вам это нужно? Есть проблемы с текущим решением?

**Comment by iskandarshabaev** [comment]
На данный момент такой опции нет. Подскажите, для чего вам это нужно? Есть проблемы с текущим решением?

**Comment by dormantpanda** [comment]
Спасибо за ответ. Согласован такой дизайн в приложении, чтобы было единообразие с ios, где это возможно. Данный факт и является проблемой.

**Comment by iskandarshabaev** [comment]
Примем во внимание, спасибо за идею!
Пока такой возможности нет, возможно в будущих версиях добавим.
