### ISSUE TITLE
CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by mikhail-timofeev-epam** [yoomoney/yookassa-android-sdk#67]
Запустил ваш пример из сэмпла и из стора (https://play.google.com/store/apps/details?id=ru.yoo.sdk.kassa.payments.example) и столкнулся с данной ошибкой на Android 5.0 (21 API). Одинакого появляется на реальном устройстве, так и на эмуляторе.

`01-14 22:45:54.947 13505-13613/ru.yoo.sdk.kassa.payments.example D/YooKassa.SDK: Load payment option list: error: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
    RequestExecutionException(request=Request{method=GET, url=https://sdk.yookassa.ru/api/frontend/v3/payment_options?amount=1.00&currency=RUB, headers=[accept:application/json, Authorization:Basic dGVzdF9OemN5TkRNM2VaTWprMzlQd3BWLU1tYzAxMTVnZWQwYTlNdUdENzl4QTFZOg==]}, e=javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.)`

![image](https://user-images.githubusercontent.com/22315416/104642011-e6757180-56c3-11eb-882c-5ccca5da37a9.png)

**Comment by iskandarshabaev** [comment]
Исправили цепочку сертификатов на сервере. Должно помочь.
Попробуйте пожалуйста ещё раз.
