### ISSUE TITLE
Цвет текста отображается некорректно

### ISSUE THREAD

**Issue by AdislanSaidov** [yoomoney/yookassa-android-sdk#69]
[1](https://prnt.sc/10eo3yr)
[2](https://prnt.sc/10eo3ix)
Раньше такого не было

**Comment by AdislanSaidov** [comment]
Стоит последняя версия либы 5.0.3
У вас в гайде по миграции 5.1.0 указана, хотя такой еще нет https://github.com/yoomoney/yookassa-android-sdk/blob/master/MIGRATION.md

**Comment by AdislanSaidov** [comment]
Похоже, дело было в Jetifier. Данная проблема возникала в Android Studio 4.2 Beta 5 с флагом enableJetifier=false, попробовал собрать в стабильной Android Studio 4.1.2 enableJetifier=true (с false не собирало) и проблема исчезла, не знаю точно, что повлияло

**Comment by AdislanSaidov** [comment]
хотя я ошибся, проблема возникает только в релизной сборке

**Comment by iskandarshabaev** [comment]
Да, есть такой баг. Скорее всего у вас включена оптимизация shrinkResources=true
В предстоящем релизе выкатим обновление с исправлением. Скорее всего на этой неделе.

Пока могу предложить переопределить цвет у себя в приложении в `res/values/colors.xml`
`<color name="ym_text_primary" tools:override="true" tools:ignore="MissingDefaultResource">#000000</color>`

И добавить этот цвет в keep в `res/raw/keep.xml`
```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools" tools:keep="@color/ym_text_primary"/>
```

**Comment by AdislanSaidov** [comment]
Спасибо!

**Comment by Lexfoxer** [comment]
В дополнение ответа https://github.com/yoomoney/yookassa-android-sdk/issues/69#issuecomment-793569870

Полный текст кода в файле `res/values/colors.xml` (если он раньше не был создан)
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <color
    name="ym_text_primary"
    xmlns:tools="http://schemas.android.com/tools"
    tools:override="true"
    tools:ignore="MissingDefaultResource"
  >#000000</color>
</resources>
```
