### ISSUE TITLE
Неверные правила Proguard/R8

### ISSUE THREAD

**Issue by princeparadoxes** [yoomoney/yookassa-android-sdk#72]
Добрый день!
В вашей библиотеке
ru.yoo.sdk.auth:auth
есть такое правило Proguard/R8
```
-keep public class * {
    public protected *;
}
```
В итоге R8 мерджит все proguard.txt из библиотек. 
Из-за этого правила обфускация на проекте можно сказать, что не работает. 
Было бы круто, если бы вы ограничили правило только своими пакетами
```
-keep public class ru.yoo.sdk.** {
    public protected *;
}
```

**Comment by iskandarshabaev** [comment]
Добрый день!
Спасибо что заметили и написали сюда. Уже взяли в работу, в ближайшее время выкатим релиз.

**Comment by iskandarshabaev** [comment]
Исправили в [версии 5.1.2](https://github.com/yoomoney/yookassa-android-sdk/releases/tag/5.1.2)
