### ISSUE TITLE
Bintray will be shutdown

### ISSUE THREAD

**Issue by farafonoff** [yoomoney/yookassa-android-sdk#74]
Please move binaries to other hosting
https://habr.com/ru/news/t/549104/
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Actual error (from 12th of April)

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve ru.yoo.sdk.kassa.payments:yookassa-android-sdk:5.1.2.
     Required by:
         project :app > project :react-native-yandex-payment
      > Could not resolve ru.yoo.sdk.kassa.payments:yookassa-android-sdk:5.1.2.
         > Could not get resource 'https://dl.bintray.com/yoomoney/maven/ru/yoo/sdk/kassa/payments/yookassa-android-sdk/5.1.2/yookassa-android-sdk-5.1.2.pom'.
            > Could not HEAD 'https://dl.bintray.com/yoomoney/maven/ru/yoo/sdk/kassa/payments/yookassa-android-sdk/5.1.2/yookassa-android-sdk-5.1.2.pom'. Received status code 403 from server: Forbidden
   > Could not resolve ru.yoo.sdk.auth:auth:1.0.51.
     Required by:
         project :app > project :react-native-yandex-payment
      > Could not resolve ru.yoo.sdk.auth:auth:1.0.51.
         > Could not get resource 'https://dl.bintray.com/yoomoney/maven/ru/yoo/sdk/auth/auth/1.0.51/auth-1.0.51.pom'.
            > Could not HEAD 'https://dl.bintray.com/yoomoney/maven/ru/yoo/sdk/auth/auth/1.0.51/auth-1.0.51.pom'. Received status code 403 from server: Forbidden

**Comment by iskandarshabaev** [comment]
Уже переносим либу

**Comment by CesPaul** [comment]
Пожалуйста, исправьте в разделе "Подключение зависимостей" инструкцию по добавлению через Gradle с учётом переноса библиотеки.

**Comment by farafonoff** [comment]
В документации также есть ссылка на проблемную библиотеку   ru.yoo.sdk.auth:auth:1.0.51, ее гитхаба я не нашел

 > Could not resolve ru.yoo.money.sdk:ui-lib:1.24.0.
     Required by:
         project :app > project :react-native-yandex-payment > ru.yoo.sdk.auth:auth:1.0.51
         project :app > project :react-native-yandex-payment > ru.yoo.sdk.auth:auth:1.0.51 > ru.yoo.sdk.auth:ui:1.0.51
      > Could not resolve ru.yoo.money.sdk:ui-lib:1.24.0.
         > Could not get resource 'https://dl.bintray.com/yoomoney/maven/ru/yoo/money/sdk/ui-lib/1.24.0/ui-lib-1.24.0.pom'.
            > Could not GET 'https://dl.bintray.com/yoomoney/maven/ru/yoo/money/sdk/ui-lib/1.24.0/ui-lib-1.24.0.pom'. Received status code 403 from server: Forbidden

**Comment by Cigan12** [comment]
> Пожалуйста, исправьте [инструкцию по добавлению через Gradle](https://github.com/yoomoney/yookassa-android-sdk#%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-gradle) с учётом переноса библиотеки:
> 
> Убрать:
> 
> repositories {
>       ~maven { url 'https://dl.bintray.com/yoomoney/maven' }~
> }
> Заменить:
> 
> dependencies {
>     ~implementation 'ru.yoo.sdk.kassa.payments:yookassa-android-sdk:5.1.2'~
>     implementation 'ru.yoomoney.sdk.kassa.payments:yookassa-android-sdk:5.1.3'
> }
> [MvnRepository](https://mvnrepository.com/artifact/ru.yoomoney.sdk.kassa.payments/yookassa-android-sdk/5.1.3)
Это помогло избежать ошибки, которая в issue, спасибо, но теперь как обновить импорты?
![image](https://user-images.githubusercontent.com/42859813/117529485-f7931700-b001-11eb-98b2-c0e355aead17.png)
Раньше у меня были такого плана импорты
А теперь вот такая проблема и вот такие " import ru.yoomoney.sdk.kassa.payments.Amount;" не работают
![image](https://user-images.githubusercontent.com/42859813/117529515-2c06d300-b002-11eb-96ab-9363afb9c4f2.png)

**Comment by Cigan12** [comment]
> > Пожалуйста, исправьте [инструкцию по добавлению через Gradle](https://github.com/yoomoney/yookassa-android-sdk#%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-gradle) с учётом переноса библиотеки:
> > Убрать:
> > repositories {
> > ~maven { url 'https://dl.bintray.com/yoomoney/maven' }~
> > }
> > Заменить:
> > dependencies {
> > ~implementation 'ru.yoo.sdk.kassa.payments:yookassa-android-sdk:5.1.2'~
> > implementation 'ru.yoomoney.sdk.kassa.payments:yookassa-android-sdk:5.1.3'
> > }
> > [MvnRepository](https://mvnrepository.com/artifact/ru.yoomoney.sdk.kassa.payments/yookassa-android-sdk/5.1.3)
> > Это помогло избежать ошибки, которая в issue, спасибо, но теперь как обновить импорты?
> > ![image](https://user-images.githubusercontent.com/42859813/117529485-f7931700-b001-11eb-98b2-c0e355aead17.png)
> > Раньше у меня были такого плана импорты
> > А теперь вот такая проблема и вот такие " import ru.yoomoney.sdk.kassa.payments.Amount;" не работают
> > ![image](https://user-images.githubusercontent.com/42859813/117529515-2c06d300-b002-11eb-96ab-9363afb9c4f2.png)

![image](https://user-images.githubusercontent.com/42859813/117573639-4379b500-b103-11eb-93a8-e7a05a456636.png)
Мой вопрос был решен вот так, просто почему то перестал работать автокомплит)

**Comment by svshishkina** [comment]
> В документации также есть ссылка на проблемную библиотеку ru.yoo.sdk.auth:auth:1.0.51, ее гитхаба я не нашел
> 
> > Could not resolve ru.yoo.money.sdk:ui-lib:1.24.0.
> > Required by:
> > project :app > project :react-native-yandex-payment > ru.yoo.sdk.auth:auth:1.0.51
> > project :app > project :react-native-yandex-payment > ru.yoo.sdk.auth:auth:1.0.51 > ru.yoo.sdk.auth:ui:1.0.51
> > > Could not resolve ru.yoo.money.sdk:ui-lib:1.24.0.
> > > Could not get resource 'https://dl.bintray.com/yoomoney/maven/ru/yoo/money/sdk/ui-lib/1.24.0/ui-lib-1.24.0.pom'.
> > > Could not GET 'https://dl.bintray.com/yoomoney/maven/ru/yoo/money/sdk/ui-lib/1.24.0/ui-lib-1.24.0.pom'. Received status code 403 from server: Forbidden

Подскажите, какую версию использовали? Подключила "ru.yoomoney.sdk.auth:auth:1.2.8", по [Migration Guid](https://github.com/yoomoney/yookassa-android-sdk/blob/master/MIGRATION.md##5---5) удалила ui-lib.aar.

Сейчас при открытии шторки оплаты на фоне черный экран и приложение крешится при попытке оплаты через кошелек.

`java.lang.NoSuchMethodError: No direct method <init>(Lru/yoomoney/sdk/auth/Config$Origin;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lru/yoomoney/sdk/auth/Config$ProcessType;Lru/yoomoney/sdk/auth/PhoneIdentifier;Lru/yoomoney/sdk/auth/ThemeScheme;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/Integer;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lru/yoomoney/sdk/auth/RemoteConfig;ZLru/yoomoney/sdk/auth/PrefilledData;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lru/yoomoney/sdk/auth/Config; or its super classes (declaration of 'ru.yoomoney.sdk.auth.Config' appears in /data/app/ru.labirint.android.debug-n6GupvUfMmhjAyCcx_E30w==/base.apk!classes6.dex)`

**Comment by iskandarshabaev** [comment]
Обновили библиотеку, новая версия `ru.yoomoney.sdk.kassa.payments:yookassa-android-sdk:5.1.4` доступна на mavenCentral

Нужно заменить старый ~~`maven { url 'https://dl.bintray.com/yoomoney/maven' }`~~ на mavenCentral в репозиториях
```
repositories {
    mavenCentral()
}
```


А так-же заменить старую версию библиотеки 
~~`implementation 'ru.yoo.sdk.kassa.payments:yookassa-android-sdk:5.1.2'`~~
на новую:

```
dependecies {
    implementation 'ru.yoomoney.sdk.kassa.payments:yookassa-android-sdk:5.1.4'
}
```

Прошу обратить внимание на то что обновился group библиотеки `ru.yoomoney.sdk.kassa.payments`
А вместе с ним обновились пакеты самой библиотеки.
В проекте нужно будет заменить импорты:
`ru.yoo.sdk.kassa.payments` -> `ru.yoomoney.sdk.kassa.payments`
