### ISSUE TITLE
Креш при оплате через кошелек

### ISSUE THREAD

**Issue by svshishkina** [yoomoney/yookassa-android-sdk#75]
Подключенные версии библиотек 

implementation 'ru.yoomoney.sdk.kassa.payments:yookassa-android-sdk:5.1.3'
implementation "ru.yoomoney.sdk.auth:auth:1.2.8"

После подключения этих версий появились две проблемы:
1. Черный фон при открытии шторки оплаты
2. Креш при попытке оплаты через кошелек

java.lang.NoSuchMethodError: No direct method <init>(Lru/yoomoney/sdk/auth/Config$Origin;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lru/yoomoney/sdk/auth/Config$ProcessType;Lru/yoomoney/sdk/auth/PhoneIdentifier;Lru/yoomoney/sdk/auth/ThemeScheme;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/Integer;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lru/yoomoney/sdk/auth/RemoteConfig;ZLru/yoomoney/sdk/auth/PrefilledData;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lru/yoomoney/sdk/auth/Config; or its super classes (declaration of 'ru.yoomoney.sdk.auth.Config' appears in /data/app/com.package-n6GupvUfMmhjAyCcx_E30w==/base.apk!classes6.dex)

**Comment by iskandarshabaev** [comment]
Попробуйте пожалуйста подключить версию `ru.yoomoney.sdk.kassa.payments:yookassa-android-sdk:5.1.4`
