### ISSUE TITLE
Безопастная сделка

### ISSUE THREAD

**Issue by Defuera** [yoomoney/yookassa-android-sdk#78]
Подскажите пожалуйста реализован ли в SDK функционал для безопасной сделки? Спасибо

В документации ничего по этому поводу не нашел

**Comment by Defuera** [comment]
👀

**Comment by iskandarshabaev** [comment]
@Defuera
Добрый день.
Извиняюсь за поздний ответ. Напишите, пожалуйста, по данной функци нашему менеджеру на почту: pbatalova@yoomoney.ru
