### ISSUE TITLE
Бесконечный лоадер при оплате через google pay

### ISSUE THREAD

**Issue by Yadro** [yoomoney/yookassa-android-sdk#81]
Если установить `paymentMethodTypes` `GOOGLE_PAY`, то открывается окно с бесконечным лоадером
```java
PaymentParameters parameters = new PaymentParameters(
    new Amount(BigDecimal.valueOf(summ), Currency.getInstance("RUB")),
    title,
    desc,
    "test_AAAAAAAAAAAAAAAAAAAA",
    "12345",
    SavePaymentMethod.USER_SELECTS,
    Collections.singleton(PaymentMethodType.GOOGLE_PAY),
    null,
    null,
    null,
    new GooglePayParameters(),
    CLIENT_ID
);
```
![Screenshot 2021-06-24 175618](https://user-images.githubusercontent.com/3994873/123286621-bc4b9980-d516-11eb-81d9-808d21896654.png)

Логи только такие:
```
2021-06-24 18:03:21.581 2516-2516/ru.animalphone.app W/DynamiteModule: Local module descriptor class for providerinstaller not found.
2021-06-24 18:03:21.590 2516-2516/ru.animalphone.app W/ProviderInstaller: Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
```
Прошу помощи :)

**Comment by iskandarshabaev** [comment]
Не подскажите? Вы уже сообщили менеджеру, что собираетесь проводить платежи с помощью мобильного SDK?
https://yookassa.ru/developers/payment-forms/android-sdk#using-sdk

**Comment by Yadro** [comment]
Заметил комент в доке
> Протестировать можно только два способа оплаты: банковские карты и ЮMoney.
На тестовом магазине я не смогу протестить gPay и applePay оплату?

**Comment by iskandarshabaev** [comment]
@Yadro К сожалению нет
