### ISSUE TITLE
Вылет при открытии формы

### ISSUE THREAD

**Issue by EclipseAndrey** [yoomoney/yookassa-android-sdk#82]
I/TextInputLayout( 6169): EditText added is not a TextInputEditText. Please switch to using that class instead.
W/DynamiteModule( 6169): Local module descriptor class for providerinstaller not found.
I/DynamiteModule( 6169): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller( 6169): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
D/AndroidRuntime( 6169): Shutting down VM
E/AndroidRuntime( 6169): FATAL EXCEPTION: main
E/AndroidRuntime( 6169): Process: xxx.xxx.xxx, PID: 6169
E/AndroidRuntime( 6169): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/threatmetrix/TrustDefender/TrustDefender;
E/AndroidRuntime( 6169): 	at a.a.a.a.a.b.e.get(:3)
E/AndroidRuntime( 6169): 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
E/AndroidRuntime( 6169): 	at a.a.a.a.a.a.e2.l.get(:1)
E/AndroidRuntime( 6169): 	at a.a.a.a.a.a.e2.n.get(:1)
E/AndroidRuntime( 6169): 	at a.a.a.a.a.a.e2.o.get(:1)
E/AndroidRuntime( 6169): 	at androidx.lifecycle.ViewModelKeyedFactory.create(Unknown Source:20)
E/AndroidRuntime( 6169): 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
E/AndroidRuntime( 6169): 	at a.a.a.a.a.a.e1$a.invoke(:1)
E/AndroidRuntime( 6169): 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
E/AndroidRuntime( 6169): 	at a.a.a.a.a.a.e1.a(Unknown Source:2)
E/AndroidRuntime( 6169): 	at a.a.a.a.a.a.e1.onViewCreated(:4)
E/AndroidRuntime( 6169): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
E/AndroidRuntime( 6169): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
E/AndroidRuntime( 6169): 	at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2236)
E/AndroidRuntime( 6169): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2009)
E/AndroidRuntime( 6169): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1965)
E/AndroidRuntime( 6169): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
E/AndroidRuntime( 6169): 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
E/AndroidRuntime( 6169): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 6169): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6169): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 6169): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 6169): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6169): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 6169): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 6169): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.threatmetrix.TrustDefender.TrustDefender" on path: DexPathList[[zip file "/data/app/~~SNaPdQ9Z1JwefRC0kqnhdg==/xxx.xxx.xxx-1dxCYTM5xuhpC-eB06BSXA==/base.apk"],nativeLibraryDirectories=[/data/app/~~SNaPdQ9Z1JwefRC0kqnhdg==/xxx.xxx.xxx-1dxCYTM5xuhpC-eB06BSXA==/lib/x86, /data/app/~~SNaPdQ9Z1JwefRC0kqnhdg==/xxx.xxx.xxx-1dxCYTM5xuhpC-eB06BSXA==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime( 6169): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime( 6169): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 6169): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 6169): 	... 25 more
I/Process ( 6169): Sending signal. PID: 6169 SIG: 9
Lost connection to device.

**Comment by EclipseAndrey** [comment]
implementation 'ru.yoomoney.sdk.kassa.payments:yookassa-android-sdk:5.1.4'
    implementation fileTree(dir: "libs", include: ['*.jar', '*.aar'])
    implementation "ru.yoomoney.sdk.auth:auth:1.2.8"

**Comment by iskandarshabaev** [comment]
@EclipseAndrey В `libs` положили файл `ThreatMetrix Android SDK 5.4-73.aar`?
https://github.com/yoomoney/yookassa-android-sdk#подключение-через-gradle

**Comment by EclipseAndrey** [comment]
> @EclipseAndrey В `libs`положили файл `ThreatMetrix Android SDK 5.4-73.aar`?
> [https://github.com/yoomoney/yookassa-android-sdk#подключение-через-gradle](https://github.com/yoomoney/yookassa-android-sdk#%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-gradle)

![Screenshot_2](https://user-images.githubusercontent.com/60741536/123641653-2623b600-d82b-11eb-9451-19080e1eb2e9.png)

**Comment by iskandarshabaev** [comment]
@EclipseAndrey Папку `libs` нужно создать в самом модуле `app`
