### ISSUE TITLE
Вылет при запуске (интеграция с flutter)

### ISSUE THREAD

**Issue by EclipseAndrey** [yoomoney/yookassa-android-sdk#84]
![photo_2021-06-29_01-08-41](https://user-images.githubusercontent.com/60741536/123748818-629ff200-d8bd-11eb-93b9-79bf0ab91fc2.jpg)

**Comment by iskandarshabaev** [comment]
@EclipseAndrey Пока не совсем понимаю как это может быть связано с sdk, а вот такое добавлять пробовали?
https://stackoverflow.com/questions/52795414/flutter-app-drops-java-lang-unsatisfiedlinkerror-couldnt-find-libflutter-so

**Comment by EclipseAndrey** [comment]
> @EclipseAndrey Пока не совсем понимаю как это может быть связано с sdk, а вот такое добавлять пробовали?
> https://stackoverflow.com/questions/52795414/flutter-app-drops-java-lang-unsatisfiedlinkerror-couldnt-find-libflutter-so

Пробовал, не помогло

**Comment by EclipseAndrey** [comment]
> @EclipseAndrey Пока не совсем понимаю как это может быть связано с sdk, а вот такое добавлять пробовали?
> https://stackoverflow.com/questions/52795414/flutter-app-drops-java-lang-unsatisfiedlinkerror-couldnt-find-libflutter-so

Если нет доступа к облачным библиотекам, например, из Украины. То запускается приложение и вылетает только при попытке оплатить

**Comment by irininaelena** [comment]
@EclipseAndrey а можно результат команды flutter doctor -v ?

**Comment by EclipseAndrey** [comment]
> @EclipseAndrey а можно результат команды flutter doctor -v ?

![image](https://user-images.githubusercontent.com/60741536/123761304-5cfcd900-d8ca-11eb-9564-579402896044.png)

**Comment by iskandarshabaev** [comment]
@EclipseAndrey К сожалению на данный момент поддерживаем только нативную разработку.
Судя по логу не хватает libflutter.so библиотеки. Можно попробовать глянуть https://github.com/flutter/flutter/issues/32756 возможно там найдётся решение. Я бы ещё попробовал глянуть есть ли этот артефакт в самой apk.
Вот тут есть репозиторий с неофициальным примером интеграции с flutter, возможно будет полезным:
https://github.com/RequemOfSouls/yandex_kassa
